td3: ../TD1/posixHelpers.cpp countdown.cpp periodicTimer.cpp timer.cpp b.cpp
	g++ -Wall -Wextra -O3 ../TD1/posixHelpers.cpp countDown.cpp periodicTimer.cpp timer.cpp b.cpp -o build/countdown -lrt

td2: chrono.cpp a.cpp ../TD1/posixHelpers.cpp
	g++ -Wall -Wextra -O3 chrono.cpp ../TD1/posixHelpers.cpp a.cpp -o build/chrono -lrt

clean: 
	rm -rvf build/*