td6: ../TD1/posixHelpers.cpp ../TD4/src/1/PosixThread.cpp ../TD4/src/1/Thread.cpp ../TD4/src/2/Mutex.cpp  ../TD4/src/3/Semaphore.cpp ../TD4/src/4/Fifo.hpp src/ActiveCalc.cpp src/ActiveObject.cpp src/Calculator.cpp src/Client.cpp src/CrunchReq.cpp src/Request.cpp src/RequestFifo.cpp src/main.cpp
	g++ -Wall -Wextra -O3 ../TD1/posixHelpers.cpp ../TD4/src/1/PosixThread.cpp ../TD4/src/1/Thread.cpp ../TD4/src/2/Mutex.cpp  ../TD4/src/3/Semaphore.cpp ../TD4/src/4/Fifo.hpp src/ActiveCalc.cpp src/ActiveObject.cpp src/Calculator.cpp src/Client.cpp src/CrunchReq.cpp src/Request.cpp src/RequestFifo.cpp src/main.cpp -o build/active.out -lrt -pthread

clean: 
	rm -rvf build/*