td41: ../TD1/posixHelpers.cpp src/1/PosixThread.cpp src/1/Thread.cpp src/1/Incrementer.cpp src/1/a.cpp
	g++ -Wall -Wextra -O3 ../TD1/posixHelpers.cpp src/1/PosixThread.cpp src/1/Thread.cpp src/1/Incrementer.cpp src/1/a.cpp -o build/posixthread -lrt -pthread

clean: 
	rm -rvf build/*